services:
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile-backend
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "backend.app:app"]

  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile-frontend
    ports:
      - "80:8501"
    command: ["streamlit", "run", "frontend/app.py"]